### Register a user
POST http://localhost:4000/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwibmFtZSI6IkFkbWluIFVzZXIiLCJpYXQiOjE3ODk1MTk5NzEsImV4cCI6MTc4OTU0ODc3MX0.V22gaRozOoiIX1GLvQ1S3S_3k4AkZnr7JMxRiFWe-D8

{
  "name": "Alaa",
  "email": "commercial6@test.com",
  "password": "12341234",
  "role": "COMMERCIAL"
}
###test login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123"
}
